"""Enumerations for Phase 9 opportunity ranking."""

from __future__ import annotations

from enum import StrEnum


RANKING_METHOD_VERSION = "ranking_v1"


class RankingStatus(StrEnum):
    RANKED = "RANKED"
    EXCLUDED = "EXCLUDED"
    UNRANKED = "UNRANKED"


class PriorityBand(StrEnum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    REVIEW = "REVIEW"


class FactorEffect(StrEnum):
    INCREASED = "INCREASED"
    DECREASED = "DECREASED"
    NEUTRAL = "NEUTRAL"
    INFORMATIONAL = "INFORMATIONAL"


class UnrankedReason(StrEnum):
    MISSING_ASSESSMENT = "MISSING_ASSESSMENT"
    FAILED_ASSESSMENT = "FAILED_ASSESSMENT"
    NON_PRODUCTION_ASSESSMENT = "NON_PRODUCTION_ASSESSMENT"
    ASSESSMENT_REVISION_MISMATCH = "ASSESSMENT_REVISION_MISMATCH"
    ELIGIBILITY_REVISION_MISMATCH = "ELIGIBILITY_REVISION_MISMATCH"
    INELIGIBLE = "INELIGIBLE"
    LIFECYCLE_NOT_ACTIONABLE = "LIFECYCLE_NOT_ACTIONABLE"


class ExclusionReason(StrEnum):
    INELIGIBLE = "INELIGIBLE"
    LIFECYCLE_CLOSED = "LIFECYCLE_CLOSED"
    LIFECYCLE_EXPIRED = "LIFECYCLE_EXPIRED"
