"""Enumerations for search strategy (Phase 4)."""

from __future__ import annotations

from enum import StrEnum


class RevisionStatus(StrEnum):
    ACTIVE = "ACTIVE"
    SUPERSEDED = "SUPERSEDED"


class RevisionChangeSource(StrEnum):
    INITIAL_SEED = "INITIAL_SEED"
    MANUAL = "MANUAL"
    STRUCTURED_EDIT = "STRUCTURED_EDIT"
    CONVERSATION_CONFIRMED = "CONVERSATION_CONFIRMED"
    IMPORT = "IMPORT"


class PreferenceStrength(StrEnum):
    STRONGLY_PREFERRED = "STRONGLY_PREFERRED"
    PREFERRED = "PREFERRED"
    ACCEPTABLE = "ACCEPTABLE"
    LESS_PREFERRED = "LESS_PREFERRED"


class StrategyCriterionCategory(StrEnum):
    PREFERENCE = "PREFERENCE"
    HARD_CONSTRAINT = "HARD_CONSTRAINT"


class StrategyParameterCode(StrEnum):
    ASSIGNMENT_DELIVERY_MODE = "ASSIGNMENT_DELIVERY_MODE"
    GEOGRAPHY = "GEOGRAPHY"
    ASSIGNMENT_DURATION = "ASSIGNMENT_DURATION"
    TRAVEL_PATTERN = "TRAVEL_PATTERN"
    WORK_MODE = "WORK_MODE"
    ENGAGEMENT_MODEL = "ENGAGEMENT_MODEL"


class ExclusionCode(StrEnum):
    REQUIRES_MULTI_PERSON_TEAM_OR_CONSORTIUM = (
        "REQUIRES_MULTI_PERSON_TEAM_OR_CONSORTIUM"
    )
    NATIONAL_CONSULTANT_ONLY = "NATIONAL_CONSULTANT_ONLY"
    JUNIOR_OR_INTERNSHIP = "JUNIOR_OR_INTERNSHIP"
    VOLUNTEER = "VOLUNTEER"
